name: Push models to Replicate

on:
  workflow_dispatch:
    inputs:
      model_name:
        type: string
        description: "Model name on Replicate (format: username/model-name)"
        default: "sdtechdev/clarity-upscaler-4-deployment"
        required: false

jobs:
  deploy:
    name: Deploy to Replicate and ECR
    runs-on: runs-on=${{ github.run_id }}-build/runner=4cpu-linux-x64/disk=large
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Setup Cog
        uses: replicate/setup-cog@v2
        with:
          token: ${{ secrets.REPLICATE_API_TOKEN }}

      - name: Download model weights
        run: python download_weights.py --skip-torch-cuda-test
      - run: cog build -t my-model
      # - name: Push to Replicate
      #   run: cog push r8.im/${{ inputs.model_name || vars.DEFAULT_MODEL_NAME }}
  deploy-gpu:
    name: Deploy to Replicate and ECR
    runs-on: runs-on=${{ github.run_id }}-build/runner=gpu
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Setup Cog
        uses: replicate/setup-cog@v2
        with:
          token: ${{ secrets.REPLICATE_API_TOKEN }}
      - name: Download model weights
        run: python download_weights.py --skip-torch-cuda-test
      - run: cog build -t my-model
