name: Push models to Replicate

on:
    workflow_dispatch:
        inputs:
            model_name:
                type: string
                description: "Model name on Replicate (format: username/model-name)"
                default: "sdtechdev/clarity-upscaler-4-deployment"
                required: true


jobs:
    push_to_replicate:
        name: Push to Replicate
        runs-on: ubuntu-latest
        steps:
            - name: Push to Replicate
              run: |
                echo "Pushing model to Replicate"
            
            - name: Free disk space
              uses: jlumbroso/free-disk-space@v1.3.1
              with:
                tool-cache: false
                docker-images: false
            
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Cog
              uses: replicate/setup-cog@v2
              with:
                token: ${{ secrets.REPLICATE_API_TOKEN }}
            
            - name: Download model weights
              run: python download_weights.py --
            
            - name: Push to Replicate
              run: cog push r8.im/${{ inputs.model_name || vars.DEFAULT_MODEL_NAME }}